notifications:
  email:
    on_success: never
    on_failure: never

dist: trusty

sudo: false

branches:
  only:
    - master
    - production

language: node_js
node_js:
  - "8.9.3"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --force

script:
  - yarn lint
  - yarn build
  - yarn test
